version: "3.9"
services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_touristo
      - POSTGRES_SERVER=127.0.0.1

  app:
    build: .
    container_name: touristo
    command: pytest app/tests/tests.py
    volumes:
      - .:/app
    depends_on:
      - db
