version: "3.9"
services:
  app:
    build: .
    container_name: touristo
    command: uvicorn app.main:fastapi_app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - SQLITE_PATH=/sql_app.db
    volumes:
      - .:/app
