"""Add user table

Revision ID: 278b63fd24a0
Revises: cf497914a6ca
Create Date: 2022-04-16 22:20:16.918158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278b63fd24a0'
down_revision = 'cf497914a6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
