"""Create users

Revision ID: 68ebe43a31bc
Revises: 863492d8fe9f
Create Date: 2022-04-16 22:32:04.831603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ebe43a31bc'
down_revision = '863492d8fe9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
