"""Create users

Revision ID: 863492d8fe9f
Revises: 278b63fd24a0
Create Date: 2022-04-16 22:26:57.810578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863492d8fe9f'
down_revision = '278b63fd24a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
