name: Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linter (flake8)
        run: flake8 .
      - name: Tests
        run: pytest app/tests/tests.py
